config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/madgeek-arc/Statistic-chart-generator:
      branch: master
      repo: https://github.com/madgeek-arc/Statistic-chart-generator.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/madgeek-arc/Statistic-chart-generator git:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-amber-elephant.sh
        container: qc.acc_woolly-blue-crane
  QC.Doc:
    repos:
      github.com/madgeek-arc/Statistic-chart-generator find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-pumpkin-affenpinscher.sh
        container: qc.doc_homey-lemon-coral
      github.com/madgeek-arc/Statistic-chart-generator git:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-chocolate-angora.sh
        container: qc.doc_nippy-alizarin-corgi
      github.com/madgeek-arc/Statistic-chart-generator markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-aquamarine-ferret.sh
        container: qc.doc_hilly-razzmatazz-lemur
  QC.Lic:
    repos:
      github.com/madgeek-arc/Statistic-chart-generator licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-crimson-octopus.sh
        container: qc.lic_woolly-linen-octopus
  QC.Sty:
    repos:
      github.com/madgeek-arc/Statistic-chart-generator checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.messy-red-goose.sh
        container: qc.sty_ready-sepia-dog
      github.com/madgeek-arc/Statistic-chart-generator hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-puce-flounder.sh
        container: qc.sty_surly-seashell-discus
      github.com/madgeek-arc/Statistic-chart-generator jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-chestnut-chipmunk.sh
        container: qc.sty_queasy-wisteria-paradise
  QC.Ver:
    repos:
      github.com/madgeek-arc/Statistic-chart-generator get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-mauve-dhole.sh
        container: qc.ver_sunny-fuchsia-chameleon
timeout: 5400
