config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/madgeek-arc/Statistic-chart-generator:
      branch: master
      repo: https://github.com/madgeek-arc/Statistic-chart-generator.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/madgeek-arc/Statistic-chart-generator git:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-celadon-retriever.sh
        container: qc.acc_geeky-salmon-heron
  QC.Doc:
    repos:
      github.com/madgeek-arc/Statistic-chart-generator find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-pink-setter.sh
        container: qc.doc_cozy-apricot-sheepdog
      github.com/madgeek-arc/Statistic-chart-generator git:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-xanthic-newfoundland.sh
        container: qc.doc_shaky-ochre-tortoise
      github.com/madgeek-arc/Statistic-chart-generator markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-corn-uakari.sh
        container: qc.doc_beady-wisteria-opossum
  QC.Lic:
    repos:
      github.com/madgeek-arc/Statistic-chart-generator licensee:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-beige-cuscus.sh
        container: qc.lic_ugly-cinnabar-saola
  QC.Sty:
    repos:
      github.com/madgeek-arc/Statistic-chart-generator checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.surly-sapphire-ant.sh
        container: qc.sty_stuffy-celadon-robin
      github.com/madgeek-arc/Statistic-chart-generator hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-alizarin-albatross.sh
        container: qc.sty_skimpy-ruby-jaguar
      github.com/madgeek-arc/Statistic-chart-generator jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-lavender-ferret.sh
        container: qc.sty_tacky-ochre-abyssinian
  QC.Ver:
    repos:
      github.com/madgeek-arc/Statistic-chart-generator get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-azure-tortoise.sh
        container: qc.ver_goopy-silver-corgi
timeout: 5400
